[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
favourites = "7wKuKurRWfEcesYa63om4zfZa2sA89BXejgezwWDEYn2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run jest --preset ts-jest"
